name: tfc-api-driven-workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Replace with your directory, relative to the root of the project
      - 'terraform/**.tf'

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  TF_DIRECTORY: "./terraform"
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  terraform-api-driven:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        name: Checkout tfc github-actions #only required whilst actions are private
        with:
          repository: hashicorp/tfc-workflows-github
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/tfc-workflows-github

      - name: Upload configuration version
        uses: ./.github/actions/tfc-workflows-github/actions/upload-configuration/
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.TF_DIRECTORY }}
          
      - name: Run Terraform Plan
        uses: ./.github/actions/tfc-workflows-github/actions/create-run/
        continue-on-error: true
        id: run-plan
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
      - name: Log Error
        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
        run: |
          echo "An error occurred in the previous step."
          echo "The error message was: ${{ steps.run-plan.outcome }}"
          echo "run_status: ${{ steps.run-plan.outputs.run_status }}"
          echo "run_status: ${{ steps.run-plan.outputs.plan_status }}"
          
      - name: Discard Terraform Run
        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
        uses: ./.github/actions/tfc-workflows-github/actions/discard-run/
        id: discard-run
        with:
          run: ${{ steps.run-plan.outputs.run_id }}
          comment: "Run discarded due to error ${{ steps.run-plan.outputs.plan_status }}"

      - name: Catch Error   
        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
        run: | 
          exit 1

      - uses: ./.github/actions/tfc-workflows-github/actions/plan-output
        name: Get plan output
        id: plan-output
        with:
          plan: ${{ steps.run-plan.outputs.plan_id }}
        
      - name: Reference plan output
        run: |
          echo "Plan status: ${{ steps.plan-output.outputs.plan_status }}"
          echo "Resources to Add: ${{ steps.plan-output.outputs.add }}"
          echo "Resources to Change: ${{ steps.plan-output.outputs.change }}"
          echo "Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}"

      - uses: ./.github/actions/tfc-workflows-github/actions/apply-run/
        name: Run Terraform Apply
        id: apply
        with:
          run: ${{ steps.run-plan.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"

      - uses: ./.github/actions/tfc-workflows-github/actions/show-run
        name: Show run output
        id: show-run
        with:
          run: ${{ steps.apply.outputs.run_id }}
      - run: |
          echo "Latest Run Status: ${{ steps.show-run.outputs.run_status }}"
  automation_controller_job:
    runs-on: ubuntu-latest
    name: Kick off Automation controller job
    steps:
      - name: Load the ansible-cloud action
        id: controller_job
        uses: ansible-cloud/aap_controller_action@v1.2.8
        with:
          controller_host: ${{ secrets.AAP_CONTROLLER_HOST }}
          controller_username: ${{ secrets.AAP_CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.AAP_CONTROLLER_PASSWORD }}
          job_template: "AWS - ec2 enforce owner tag"
          extra_vars: "your_region=us-west-1"
          validate_certs: false