name: tfc-api-driven-workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    #paths:
      # Replace with your directory, relative to the root of the project
    #  - 'terraform/**.tf'

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  TF_DIRECTORY: "./terraform"

jobs:
  terraform-api-driven:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Upload configuration version
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.1
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.TF_DIRECTORY }}
          
      - name: Run Terraform Plan
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.1
        continue-on-error: true
        id: run-plan
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
      - name: Log Error
        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
        run: |
          echo "An error occurred in the previous step."
          echo "The error message was: ${{ steps.run-plan.outcome }}"
          echo "run_status: ${{ steps.run-plan.outputs.run_status }}"

          
      - name: Discard Terraform Run
        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
        uses: hashicorp/tfc-workflows-github/actions/discard-run@v1.0.1
        id: discard-run
        with:
          run: ${{ steps.run-plan.outputs.run_id }}
          comment: "Run discarded due to error ${{ steps.run-plan.outputs.plan_status }}"

      - name: Catch Error   
        if: ${{ steps.run-plan.outputs.plan_status != 'finished' }} 
        run: | 
          exit 1

      - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.1
        name: Get plan output
        id: plan-output
        with:
          plan: ${{ steps.run-plan.outputs.plan_id }}
        
      - name: Reference plan output
        run: |
          echo "Plan status: ${{ steps.plan-output.outputs.plan_status }}"
          echo "Resources to Add: ${{ steps.plan-output.outputs.add }}"
          echo "Resources to Change: ${{ steps.plan-output.outputs.change }}"
          echo "Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}"
          echo 'plan_payload: ${{ steps.run-plan.outputs.payload }}'
    
      - name: Get workspace id - jq
        id: workspace_id
        run: |
          echo '${{ steps.run-plan.outputs.payload }}' > payload.json
          echo "workspace_id=$(jq -r '.included[] | select(.type == "workspaces") | .id' < payload.json)" >> $GITHUB_OUTPUT
          
      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.1
        name: Run Terraform Apply
        id: apply
        with:
          run: ${{ steps.run-plan.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"

      - uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.1
        name: Show run output
        id: showrun
        with:
          run: ${{ steps.apply.outputs.run_id }}
      - run: |
          echo "Latest Run Status: ${{ steps.showrun.outputs.run_status }}"
          echo 'payload: ${{ steps.showrun.outputs.payload }}'
          echo 'run_link: ${{ steps.showrun.outputs.run_link }}'
          echo 'run_message: ${{ steps.showrun.outputs.run_message }}'
      - name: Checkout addons
        uses: actions/checkout@v3
        with:
          ref: main
          repository: hashi-demo-lab/tfc-workflows-github-addon
          path: addon
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install-python-dep
        run: pip install -r ./addon/requirements.txt
      - name: get-workspace-outputs
        id: get-ws-outputs
        run: |
          PYTHON_OUT=$(python ./addon/get-workspace-outputs.py)
          echo "python_output=$PYTHON_OUT" >> $GITHUB_OUTPUT
        env:
          WORKSPACE_ID: ${{ steps.workspace_id.outputs.workspace_id }}
      - name: set_output
        id: set_output
        run: |
          echo "Python output: ${{ steps.get-ws-outputs.outputs.python_output }}"
          echo '${{ steps.get-ws-outputs.outputs.python_output }}' | jq -r '[.data[] | {name: .attributes.name, value: .attributes.value}]'

       #   echo "workspace_outputs=$(jq -r '[.data[] | {name: .attributes.name, value: .attributes.value}] | tojson' <  outputs.json)" >> $GITHUB_OUTPUT
  automation_controller_job:
    needs: [terraform-api-driven]
    runs-on: ubuntu-latest
    name: ansible-automation-controller-job
    continue-on-error: true
    steps:
      - name: Load the ansible-cloud action
        id: controller_job
        uses: ansible-cloud/aap_controller_action@v1.2.8
        continue-on-error: true
        with:
          controller_host: ${{ secrets.AAP_CONTROLLER_HOST }}
          controller_username: ${{ secrets.AAP_CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.AAP_CONTROLLER_PASSWORD }}
          job_template: "Demo Job Template"
          extra_vars: "{}"
          validate_certs: false