name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Replace with your directory, relative to the root of the project
      - 'terraform/**.tf'

env:
  # No need to pass as inputs to each action
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: "my-workspace"
  TF_DIRECTORY: "./terraform"
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  terraform-apply:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: hashicorp/tfc-workflows-github
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/tfc-workflows-github
      - uses: ./.github/actions/tfc-workflows-github/actions/upload-configuration/
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.TF_DIRECTORY }}

      - uses: ./.github/actions/tfc-workflows-github/actions/create-run/
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - uses: ./.github/actions/tfc-workflows-github/actions/apply-run/
        # assign id attribute to reference in subsequent steps
        id: apply
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"